---
title: "iteration_and_listcols"
author: "Nihaal Rahman"
date: "2023-10-31"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
```

Differenrt stuff with different lengths
```{r}
l = 
  list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix = matrix(1:10, nrow = 5, ncol = 2),
    summary = summary(rnorm(100))
  )
```

Accessing lists

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```

### loops

```{r}
list_norm_samples =
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )
```

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
  
}
```

### use 'map'

```{r}
output = map(list_norm_samples, mean_and_sd)

output = map(list_norm_samples, median)

output = map(list_norm_samples, summary)
```

### create DF

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm_samples
  )
```

```{r}
mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])
mean_and_sd(listcol_df$samp[[3]])

map(listcol_df$samp, mean_and_sd)

listcol_df |> 
  mutate(
    mean_sd = map(samp, mean_and_sd),
    median = map(samp, median)) |> 
  select(name, mean_sd) |> 
  unnest(mean_sd)
```

### NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))

nsduh_table <- function(html, table_num, table_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      name = table_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}

nsduh_results = 
  bind_rows(
    nsduh_table(nsduh_html, 1, "marj_one_year"),
    nsduh_table(nsduh_html, 4, "cocaine_one_year"),
    nsduh_table(nsduh_html, 5, "heroin_one_year")
  )
```

import data using a for loop

```{r}
table_input = list(1,4,5)
name_input = list("marj_one_year", "cocaine_one_year", "heroin_one_year")

output = vector("list", length = 3)

for(i in 1:3) {
  
  output[[i]] = nsduh_table(nsduh_html, table_input[[i]], name_input[[i]])
}

nsduh_df = bind_rows(output)
```


Try again, using maps!!!

```{r}
nsduh_table <- function(html, table_num, table_name) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}


nsduh_df = 
  tibble(
    name = c("marj_one_year", "cocaine_one_year", "heroin_one_year"),
    number = c(1, 4, 5)
  ) |> 
  mutate(
    table = map(number, nsduh_table, html = nsduh_html)) |> 
  unnest(table)

map(nsduh_df$number, nsduh_table, html = nsduh_html)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

weather_df
```

```{r}
weather_nest_df = 
  weather_df |> 
  nest(df = date:tmin)
```

Can I regress 'tmax' on 'tmin' for each of these...?

```{r}
central_park_df =
  weather_nest_df |> 
  pull(df) |> 
  nth(1)
```

fit a linear regression for central park

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

weather_lm(central_park_df)
```

let's try a for loop

```{r}
input_list = weather_nest_df |> pull(df)
output = vector("list", length = 3)

for (i in 1:3) {
  output[[i]] = weather_lm(input_list[[i]])
}

weather_nest_df |> 
  mutate(models = map(df, weather_lm))
```

